### ISSUE TITLE
RegistrationForm: Registrierung mit e-mail ohne TLD möglich

### ISSUE THREAD

**Issue by roli81** [Schenk-Smart-Solutions/web-components-toolbox-musigschuel#10]

**Comment by roli81** [comment]
Es ist möglich sich mit ungültigen E-Mail Adressen wie music-guy@gmail zu registrieren. @Weedshaker Bitte Regex validierung anpassen, dass eine TLD eingegeben werden muss!

![Image](https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/assets/19175156/231f7ca9-76f4-460c-bf7a-74a98f4c0cce)

**Comment by Weedshaker** [comment]
Gemäss Web Standart: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#value
username@domain or username@domain.tld

**Comment by roli81** [comment]
@Weedshaker der standard ist mir hier eigentlich egal. Es führte dazu das sich ein Benutzer zweimal registrieren konnte und die einfachste Art bist es jetzt abzufangen das keine emails ohne TLD möglich sind. Ich habs jetzt halt mal im backend gemacht aber ist halt so naja. Um die ganze Logik auf Standard umzubauen habe ich wieder zwei stunden die Registrierung ist der komplizierte Teil und sorry kein schwein hat eine email ohne tld.

**Comment by Weedshaker** [comment]
`<input type="email" name="user_email" pattern="[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}$">`
then just put the pattern attribute with the right regex into the desired input field.

**Comment by Weedshaker** [comment]
I make you an example

**Comment by Weedshaker** [comment]
da war noch ein fehler im pattern> pattern="[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}$

**Comment by Weedshaker** [comment]
siehe hier: https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/commit/e01a88b1ee800dcbc765fef9dd9a78428f44537d#diff-223e409bef811d5cb17794b434a752f76c438e2602d158d896e59c02fa6cbb71R36 oder https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/blob/master/src/es/components/pages/FormApi.html#L36

**Comment by Weedshaker** [comment]
@roli81 , der Pattern wurde noch korrigiert. [a-z0-9._%+**\**-]+@[a-z0-9.**\**-]+\.[a-z]{2,}$ 
der warf einen Error in der Dev Tools Konsole. Jetzt geht es... kann hier getestet werden: https://schenk-smart-solutions.github.io/web-components-toolbox-musigschuel/src/es/components/web-components-toolbox/docs/TemplateNoControllers.html?rootFolder=src&css=./src/css/variablesCustom.css&logo=./src/es/components/atoms/logo/default-/default-.html&nav=./src/es/components/molecules/navigation/default-/default-.html&footer=./src/es/components/organisms/footer/default-/default-.html&content=./src/es/components/pages/FormApi.html
