### ISSUE TITLE
RegisterForm: Checkboxen zu klein

### ISSUE THREAD

**Issue by roli81** [Schenk-Smart-Solutions/web-components-toolbox-musigschuel#11]

**Comment by roli81** [comment]
![Image](https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/assets/19175156/d91cf648-07ea-4ec9-a3ce-d707480fcd03)

**Comment by Weedshaker** [comment]
gonna be deployed with the next commit

**Comment by roli81** [comment]
@Weedshaker leider immernoch

**Comment by roli81** [comment]
https://musigschuel.ch/profil/

**Comment by roli81** [comment]
Login:

login: roland.schenk@hoermoos.ch
password: affenarsch

**Comment by roli81** [comment]
oh nein, inkognito ist gut, wir müssen was gegen den cache machen
