### ISSUE TITLE
RegisterForm Standorterfassung kein Fokus

### ISSUE THREAD

**Issue by roli81** [Schenk-Smart-Solutions/web-components-toolbox-musigschuel#12]

**Comment by roli81** [comment]
![Image](https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/assets/19175156/025fbf0d-4358-4062-89c2-7adbbd148521)

**Comment by Weedshaker** [comment]
gonna be deployed with next commit.
