### ISSUE TITLE
SimpleForm: Bitte Form clearen wenn abgesedet und kein Fehler und kein redirect.

### ISSUE THREAD

**Issue by roli81** [Schenk-Smart-Solutions/web-components-toolbox-musigschuel#13]

**Comment by Weedshaker** [comment]
Das ist bereits möglich indem man bei der Response das Folgende antwortet:

`
{
  response: "irgend ein String",
  clear: true
}
`

siehe: https://github.com/mits-gossau/web-components-toolbox/blob/master/src/es/components/molecules/simpleForm/SimpleForm.js#L486

**Comment by Weedshaker** [comment]
Bitte schliessen sobald nachgezogen.
