### ISSUE TITLE
Karte: geöffnete Standorte sollten sich schliessen, wenn ein neuer angeklickt wird in der Karte

### ISSUE THREAD

**Issue by roli81** [Schenk-Smart-Solutions/web-components-toolbox-musigschuel#14]

**Comment by roli81** [comment]
https://github.com/Schenk-Smart-Solutions/web-components-toolbox-musigschuel/assets/19175156/debc37da-d52a-4200-879c-f7e8b07a09f2

**Comment by Weedshaker** [comment]
gonna be deployed in the next 30min
